/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "x10 and x-8": "x10 和 x-8",
    "\t\t\tAll skills take 6 seconds less to cool down per level.": "\t\t\t每级所有技能冷却时间减少 6 秒。",
    "\t\t\tCurrently:": "\t\t\t当前：",
    "\t\t\tOverflow upgrade is 10% more effective per level.": "\t\t\t每升一级，溢出升级的效果提高 10%。",
    "\t\t\tUpgrades that costs progress points costs 5% less per level.": "\t\t\t花费进度点的升级每升一级花费减少 5%。",
    "\t\t\tYou gain 1% more bar speed from each logress point you currently have per level.": "\t\t\t每级你当前拥有的每个日志点都会增加 1% 的进度条速度。",
    "\t\t\tYou gain 100% more logress points per level.": "\t\t\t每升一级，您将获得 100% 以上的记录点。",
    "\t\"Exp\"": "\t\"经验\"",
    "\t\"Reci\"": "\t\"Reci\"",
    "\t\"Sine\"": "\t\"正弦\"",
    "\t\"Squr\"": "\t\"方格\"",
    "\tAbsolute Value": "\t绝对值",
    "\tAuto Length Upgrade": "\t自动长度升级",
    "\tAuto Overflow Upgrade": "\t自动溢出升级",
    "\tAuto Point Upgrade": "\t自动点升级",
    "\tAuto Redeem 1": "\t自动兑换1",
    "\tAuto Redeem 2": "\t自动兑换2",
    "\tAuto Speed Upgrade": "\t自动速度升级",
    "\tAuto Upgrade Magnitude": "\t自动升级幅度",
    "\tAutomatically buys bar length upgrades.": "\t自动购买杆长度升级。",
    "\tAutomatically buys bar speed upgrades.": "\t自动购买酒吧速度升级。",
    "\tAutomatically buys overflow speed upgrades.": "\t自动购买溢出速度升级。",
    "\tAutomatically buys point gain upgrades.": "\t自动购买点数增益升级。",
    "\tAutomatically redeem logress points.": "\t自动兑换对数点数。",
    "\tAutomatically redeem progress points.": "\t自动兑换进度点数。",
    "\tAutomation Unlock": "\t自动化解锁",
    "\tBar Length Upgrade": "\t进度条长度升级",
    "\tBar Speed Upgrade": "\t进度条速度升级",
    "\tComing soon...": "\t即将推出...",
    "\tCoolant": "\t冷却剂",
    "\tCooldown:": "\t冷却时间：",
    "\tCube": "\t立方",
    "\tDivides bar length by 2.": "\t将条长度除以 2。",
    "\tExp Upgrade": "\t经验值升级",
    "\tExp:": "\t经验值:",
    "\tGives you a \"BOOST\" bar for 1 minute. Fill it up by redeeming points! It gives a bar speed boost that increases exponentially up to x": "\t为您提供 1 分钟的“提升”进度条。通过兑换点数将其填满！它可以使进度条速度呈指数级增长，最高可达 x",
    "\tGives you a point gain multiplier oscillating between": "\t给你一个在之间振荡的点数增益乘数",
    "\tIncreases the buy amount for auto upgrades.": "\t增加自动升级的购买金额。",
    "\tIncreases the effect of \"Reci\".": "\t增强“Reci”的效果。",
    "\tIncreases the max multiplier from \"Exp\"": "\t增加“Exp”的最大乘数",
    "\tIncreases the multiplier from \"Sine\"": "\t增加“正弦”的乘数",
    "\tMakes \"Squr\" cube instead of square the other skills' effect.": "\t使“Squr”立方体而不是其他技能效果的平方。",
    "\tMakes discount coupons randomly appear on the screen for 1 minute! All upgrades that cost progress points' price will be divided based on the amount you click, but if you miss one, then it'll all reset!": "\t使折扣券随机出现在屏幕上1分钟！所有花费进度点价格的升级都会根据您点击的数量进行划分，但如果错过了，则全部重置！",
    "\tMultiplies bar speed by 2.": "\t将进度条速度乘以 2。",
    "\tMultiplies point gain by 2.": "\t将点增益乘以 2。",
    "\tNegative multipliers from \"Sine\" are turned positive.": "\t“正弦”的负乘数变为正数。",
    "\tOverflow Speed Upgrade": "\t溢出速度升级",
    "\tPoint Gain Upgrade": "\t点数增益升级",
    "\tReci Upgrade": "\tReci 升级",
    "\tReci:": "\t参考：",
    "\tReduces overflow penalty.": "\t减少溢出惩罚。",
    "\tReduces the time it takes for \"Squr\" to take effect.": "\t减少“Squr”生效所需的时间。",
    "\tSine Upgrade": "\t正弦升级",
    "\tSine:": "\t正弦：",
    "\tSkill Power Upgrades": "\t技能力量升级",
    "\tSkill Unlock": "\t技能解锁",
    "\tSpeed up time based on auto upgrades bought and current logress points.": "\t根据购买的自动升级和当前的 loggress 点加快时间。",
    "\tSqur Upgrade": "\tSqur 升级",
    "\tSqur:": "\tSqur：",
    "\tTake": "\t采取",
    "\tThe BOOST bar reaches the max multiplier earlier.": "\t提升进度条更早达到最大乘数。",
    "\tThe time before coupons dissappear are doubled.": "\t优惠券消失之前的时间加倍。",
    "\tTime Machine": "\t时间机器",
    "\tTwo for One Special": "\t买二送一特价",
    "\tUnlocks a new skill.": "\t解锁一项新技能。",
    "\tUnlocks the automation tab.": "\t解锁自动化选项卡。",
    "\tUnlocks the skill upgrade tab.": "\t解锁技能升级选项卡。",
    "\tYou've gotten": "\t你已经得到它了",
    "? Logress Point": "? 对数点",
    "[, and .] Select upgrade tab for max all": "[, and .] 选择升级选项卡以获取最大全部",
    "[1 - 4]: Use skills": "[1 - 4]：使用技巧",
    "[l]: Redeem Logress Points": "[l]: 兑换 Loggress 点数",
    "[left & right arrows]: Switch screen": "[左右箭头]：切换屏幕",
    "[m]: Max all upgrades": "[m]：最大所有升级",
    "[p]: Redeem Progress Points": "[p]：兑换进度点",
    "1/buy\n": "1/购买\n",
    "Amount of Times Overflowed:": "溢出次数：",
    "as you fill it up. Be carefull not to overheat!": "当你加满的时候，小心不要过热！",
    "Auto Save": "自动保存",
    "Automation": "自动化",
    "Automation Upgrades": "自动化升级",
    "Bar length is 10% shorter per level.": "每级进度条长度缩短 10%。",
    "Bar Length Upgrade Auto-Buyer": "进度条长度升级自动购买者",
    "Bar Speed Upgrade Auto-Buyer": "进度条速度升级自动买家",
    "Be fast": "动作要快",
    "Boom boom boom": "轰轰轰",
    "Cold": "寒冷",
    "Creator: TheTastyPi": "创建者： TheTastyPi",
    "Credit": "鸣谢",
    "Dark": "深色",
    "Discount Coupons Clicked:": "点击折扣券：",
    "Do something a lot of times, may or may not be related to the previous achievement": "多次做某事，可能与之前的成就相关，也可能无关",
    "Don't miss out on a whole new mechanic": "不要错过全新的机制",
    "effect": "影响",
    "Fastest Logress Point Redeem:": "最快的 Loggress 点数兑换：",
    "for 1 minute. Click it while it's high!": "1分钟，高的时候点击它！",
    "Get a single progress point.": "获取单个进度点。",
    "Go further": "走得更远",
    "Go the wrong way": "走错路",
    "hi\n": "小时\n",
    "I don't think you'll need help with this one": "我认为您在这方面不需要帮助",
    "I thought it was just a progress bar!": "我以为这只是一个进度条！",
    "I'm ticklish": "我很怕痒",
    "Idling paid off": "闲置得到了回报",
    "if you're seeing this, then something broke": "如果你看到这个，说明有东西坏了",
    "Impatient": "不耐烦",
    "in selected upgrade tab for this screen": "在此屏幕的选定升级选项卡中",
    "in total.": "总共。",
    "Infinity": "无穷",
    "Information": "信息",
    "Interval": "间隔",
    "Just keep going": "尽管继续",
    "Keep playing": "继续玩",
    "Light": "浅色",
    "Load": "加载",
    "Locked\n": "未解锁\n",
    "logress points": "洛格雷斯点",
    "Lowest Progress Points Ever:": "有史以来最低的进度点：",
    "Max All": "全部最大",
    "minutes\n": "分钟\n",
    "Nothing here...": "这里没有什么...",
    "On": "开",
    "One of each": "一人一个",
    "Overflow Upgrade Auto-Buyer": "溢出升级自动购买者",
    "point": "观点",
    "Point Gain Upgrade Auto-Buyer": "点数增益升级自动购买者",
    "Practice your reaction time": "练习你的反应时间",
    "Progression-related achievement": "与进步相关的成就",
    "Reading this is pointless": "读这个毫无意义",
    "Redeem": "兑换",
    "Redeem Points": "兑换点数",
    "s all other skills' effect for 30 seconds, but if you redeem points while it's charging, then the charging fails and you don't get the boost.": "所有其他技能的效果持续30秒，但如果你在充电时兑换点数，那么充电会失败，你不会获得加成。",
    "Saving": "保存",
    "Skill Upgrades": "技能升级",
    "Skill Uses:": "技能用途：",
    "Skills": "技能",
    "square": "正方形",
    "Statistics & Information": "统计与信息",
    "Themes": "主题",
    "Time Machine Multipler:": "时间机器多路复用器：",
    "to charge up and": "充电并",
    "Total Charges Failed:": "失败的总收费：",
    "Total Logress Points Ever:": "历史总 Loggress 点：",
    "Total Progress Points Ever:": "总进度点：",
    "until next level": "直到下一个级别",
    "Upgrades": "升级",
    "Wipe": "擦除",
    "You don't need a hint": "你不需要提示",
    "You get this when you get a really high number-not-number": "当你得到一个非常高的数字而不是数字时你就会得到这个",
    "You'll get this eventually": "你最终会得到这个",
    "Achievement Got!": "成就达成！",
    "Reach 1000%.": "达到 1000%.",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Version: ": "版本: ",
    "\t\tCurrently: ": "\t\t当前: ",
    "\t\tCost: ": "\t\t成本: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\%$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) logress points.$/, '你有 $1 对数点。'],
    [/^You have (.+) progress points.$/, '你有 $1 进度点。'],
    [/^You have (.+) progress point.$/, '你有 $1 进度点。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) hour, ([\d\.]+) minutes, and ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^([\d\.]+) day, ([\d\.]+) minute, and ([\d\.]+) seconds$/, '$1 天 $2 分钟 $3 秒'],
    [/^([\d\.]+) day, ([\d\.]+) minutes, and ([\d\.]+) seconds$/, '$1 天 $2 分钟 $3 秒'],
    [/^([\d\.]+) hours, ([\d\.]+) minutes, and ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^([\d\.]+) day, ([\d\.]+) hour, ([\d\.]+) minutes, and ([\d\.]+) seconds$/, '$1 天 $2 小时 $3 分钟 $4 秒'],
    [/^([\d\.]+) day, ([\d\.]+) hours, ([\d\.]+) minutes, and ([\d\.]+) seconds$/, '$1 天 $2 小时 $3 分钟 $4 秒'],
    [/^([\d\.]+) minute and ([\d\.]+) seconds$/, '$1 分钟 $2 秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Progress Point$/, '$1 进度点'],
    [/^([\d\.,]+) Progress Points$/, '$1 进度点'],
    [/^([\d\.,]+) Logress Point$/, '$1 对数点'],
    [/^([\d\.,]+) Logress Points$/, '$1 对数点'],
    [/^([\d\.,]+) logress points$/, '$1 对数点'],
    [/^([\d\.,]+) minutes\n$/, '$1 分钟\n'],
    [/^([\d\.,]+) Skill\n$/, '$1 技能\n'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)\/buy$/, '$1\/购买'],
    [/^\+([\d\.,]+)\%\/point$/, '\+$1\%\/购点数'],
    [/^Point Auto-Redeemer Level ([\d\.,]+)$/, '点数自动兑换等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) Progress Point$/, '成本：$1 进度点'],
    [/^Cost: (.+) Progress Points$/, '成本：$1 进度点'],
    [/^Cost: (.+) Logress Point$/, '成本：$1 对数点'],
    [/^Cost: (.+) Logress Points$/, '成本：$1 对数点'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Currently: (.+)buy$/, '当前：$1购买'],
    [/^Currently: (.+) Skills$/, '当前：$1 技能'],
    [/^Currently: Locked$/, '当前：未解锁'],
    [/^Currently: (.+)$/, '当前：$1'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);